/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package biblioteca;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class TelaBiblioteca extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(TelaBiblioteca.class.getName());
    
    private ArquivoLivro arquivo;

    private List<Livro> lista;
    private int linhaEdicao = -1;

    /**
     * Creates new form TelaBiblioteca
     */
    public TelaBiblioteca() {
        initComponents();
        arquivo = new ArquivoLivro("Livros");
        lista = arquivo.leArquivo();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTipo = new javax.swing.ButtonGroup();
        btnGrpSituacao = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        rdoFisico = new javax.swing.JRadioButton();
        rdoDigital = new javax.swing.JRadioButton();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblCategoria = new javax.swing.JLabel();
        rdoNaoIniciado = new javax.swing.JRadioButton();
        rdoAndamento = new javax.swing.JRadioButton();
        rdoConcluido = new javax.swing.JRadioButton();
        lblTipo = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        tblLivros = new javax.swing.JScrollPane();
        tblCadastrados = new javax.swing.JTable();
        lblCadastrados = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Título");

        lblAutor.setText("Autor");

        txtTitulo.setActionCommand("<Not Set>");

        lblAno.setText("Ano Publicação");

        btnGrpTipo.add(rdoFisico);
        rdoFisico.setText("Físico");

        btnGrpTipo.add(rdoDigital);
        rdoDigital.setText("Digital");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tecnologia", "Ficção", "Romance", "História" }));

        lblCategoria.setText("Categoria");

        btnGrpSituacao.add(rdoNaoIniciado);
        rdoNaoIniciado.setText("Não iniciado");

        btnGrpSituacao.add(rdoAndamento);
        rdoAndamento.setText("Em andamento");

        btnGrpSituacao.add(rdoConcluido);
        rdoConcluido.setText("Concluído");

        lblTipo.setText("Tipo");

        lblSituacao.setText("Situação de Leitura");

        tblCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Título", "Autor", "Ano Publicação", "Tipo", "Categoria", "Situação"
            }
        ));
        tblLivros.setViewportView(tblCadastrados);

        lblCadastrados.setText("Livros Cadastrados");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtAutor)
            .addComponent(txtTitulo)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAno))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoFisico)
                                .addGap(38, 38, 38)
                                .addComponent(rdoDigital))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria))))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSituacao)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoNaoIniciado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoAndamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoConcluido))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCadastrados)))
                .addGap(0, 213, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tblLivros, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditar, btnSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(lblTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoFisico)
                        .addComponent(rdoDigital)))
                .addGap(19, 19, 19)
                .addComponent(lblAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria)
                    .addComponent(lblSituacao))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNaoIniciado)
                    .addComponent(rdoAndamento)
                    .addComponent(rdoConcluido))
                .addGap(18, 18, 18)
                .addComponent(lblCadastrados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditar, btnSalvar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarTabela() {
        DefaultTableModel tabela = (DefaultTableModel) tblCadastrados.getModel();

        tabela.setRowCount(0);

        for (Livro livro : lista) {
            tabela.addRow(livro.obterDados());
        }
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String tipo;
        if (rdoDigital.isSelected()) {
            tipo = "Digital";
        } else if (rdoFisico.isSelected()) {
            tipo = "Físico";
        } else {
            JOptionPane.showMessageDialog(this, "Selecione o tipo do livro", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String situacao;
        if (rdoAndamento.isSelected()) {
            situacao = "Em andamento";
        } else if (rdoConcluido.isSelected()) {
            situacao = "Concluído";
        } else if (rdoNaoIniciado.isSelected()) {
            situacao = "Não iniciado";
        } else {
            JOptionPane.showMessageDialog(this, "Selecione a situação de leitura", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Integer numero;
        String textoAno = txtAno.getText().trim();
        if (textoAno.isEmpty()) {
            numero = null;
        } else {
            try {
                numero = Integer.parseInt(textoAno);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ano de publicação inválido", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        try {
            if (linhaEdicao == -1) {
                Livro livro = new Livro(txtTitulo.getText(), txtAutor.getText(), numero, tipo, (String) cmbCategoria.getSelectedItem(), situacao);
            lista.add(livro);
            } else {
                Livro livroAntigo = lista.get(linhaEdicao);
                Livro livro = new Livro(txtTitulo.getText(), txtAutor.getText(), numero, tipo, (String) cmbCategoria.getSelectedItem(), situacao);
                lista.set(linhaEdicao, livro);
                linhaEdicao = -1;
            }
            arquivo.gravaArquivo();
            txtTitulo.setText("");
            txtAutor.setText("");
            txtAno.setText("");
            btnGrpTipo.clearSelection();
            btnGrpSituacao.clearSelection();
            cmbCategoria.setSelectedIndex(0);
            carregarTabela();
            JOptionPane.showMessageDialog(
                    null,
                    "Dados salvos com sucesso"
                );
            } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),
                "Dados inválidos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linha = tblCadastrados.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar");
            return;
        }

        linhaEdicao = linha;

        Livro livro = lista.get(linha);
        txtTitulo.setText(livro.getTitulo());

        if (livro.getTipo().equals("Digital")) {
            rdoDigital.setSelected(true);
        } else {
            rdoFisico.setSelected(true);
        }

        if (livro.getSituacao().equals("Concluído")) {
            rdoConcluido.setSelected(true);
        } else if (livro.getSituacao().equals("Em andamento")) {
            rdoAndamento.setSelected(true);
        } else {
            rdoNaoIniciado.setSelected(true);
        }

        txtAutor.setText(livro.getAutor());
        txtAno.setText(String.valueOf(livro.getAnoPublicacao()));
        cmbCategoria.setSelectedItem(livro.getCategoria());
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup btnGrpSituacao;
    private javax.swing.ButtonGroup btnGrpTipo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCadastrados;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rdoAndamento;
    private javax.swing.JRadioButton rdoConcluido;
    private javax.swing.JRadioButton rdoDigital;
    private javax.swing.JRadioButton rdoFisico;
    private javax.swing.JRadioButton rdoNaoIniciado;
    private javax.swing.JTable tblCadastrados;
    private javax.swing.JScrollPane tblLivros;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
