/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulario;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_OPTION;

/**
 *
 * @author laboratorio
 */
public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());

    /**
     * Creates new form Formulario
     */
    public char sexo;
    public boolean astronomia, tecnologia, esportes;
    
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpSexo = new javax.swing.ButtonGroup();
        lblNome = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        RdoMasculino = new javax.swing.JRadioButton();
        RdoFeminino = new javax.swing.JRadioButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPessoas = new javax.swing.JTextArea();
        chkTecnologia = new javax.swing.JCheckBox();
        chkAstronomia = new javax.swing.JCheckBox();
        chkEsportes = new javax.swing.JCheckBox();
        cmbIdioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNome.setText("Nome:");

        lblSexo.setText("Sexo");

        btnGrpSexo.add(RdoMasculino);
        RdoMasculino.setText("Masculino");

        btnGrpSexo.add(RdoFeminino);
        RdoFeminino.setText("Feminino");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txaPessoas.setColumns(20);
        txaPessoas.setRows(5);
        jScrollPane1.setViewportView(txaPessoas);

        chkTecnologia.setText("Tecnologia");
        chkTecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTecnologiaActionPerformed(evt);
            }
        });

        chkAstronomia.setText("Astronomia");

        chkEsportes.setText("Esportes");

        cmbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portugues", "Ingles", "Espahol", "Frances", "Alemao" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkTecnologia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkAstronomia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkEsportes)
                                .addGap(0, 119, Short.MAX_VALUE))
                            .addComponent(txtNome)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSalvar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RdoMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RdoFeminino))
                            .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkTecnologia)
                    .addComponent(chkAstronomia)
                    .addComponent(chkEsportes))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSexo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RdoMasculino)
                        .addComponent(RdoFeminino)))
                .addGap(1, 1, 1)
                .addComponent(cmbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       tecnologia = chkTecnologia.isSelected();
       esportes = chkEsportes.isSelected();    
       astronomia = chkAstronomia.isSelected();
       JOptionPane.showMessageDialog(null, "Tec: "+ tecnologia + 
               "\nAstronomia: "+ astronomia+ "\nEsportes: "+ esportes, "Info", JOptionPane.INFORMATION_MESSAGE);

//radio button selecioado ou não
       if(RdoMasculino.isSelected()){
           sexo ='M';
           JOptionPane.showMessageDialog(null, "Sexo Masculino Seleionado", "Alerta", JOptionPane.OK_OPTION);
           Pessoa p = new Pessoa(txtNome.getText(), sexo, String.valueOf(cmbIdioma.getSelectedItem()));
           txaPessoas.append(p+"");
       }
       else if(RdoFeminino.isSelected()){
           JOptionPane.showMessageDialog(null, "Sexo Feminino Seleionado", "Alerta", JOptionPane.OK_OPTION);
           sexo = 'F';
           Pessoa p = new Pessoa(txtNome.getText(), sexo, String.valueOf(cmbIdioma.getSelectedItem()));
           txaPessoas.append(p+"");
       }
       else{
           JOptionPane.showMessageDialog(null, "Selecione um Sexo", "ERRO", JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chkTecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTecnologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RdoFeminino;
    private javax.swing.JRadioButton RdoMasculino;
    private javax.swing.ButtonGroup btnGrpSexo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chkAstronomia;
    private javax.swing.JCheckBox chkEsportes;
    private javax.swing.JCheckBox chkTecnologia;
    private javax.swing.JComboBox<String> cmbIdioma;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JTextArea txaPessoas;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
